# -*- coding: utf-8 -*-
"""exercicios_T13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GK_2bNYtgBrH6dY5wJGy5pCApInsdPcV
"""

# ATIVIDADE 1
numero = None

while numero is None:
    try:
        numero = int(input("Digite um numero inteiro: "))
    except ValueError:
        print("Erro!. Digite apenas numeros Tente novamente.")

print(f"Numero digitado: {numero}")

# ATIVIDADE 2
numero = -1

while numero < 0:
    numero = int(input("Digite um numero positivo: "))
    if numero < 0:
        print("ERRO! O Numero deve ser positivo.")

print(f"numero cadastrado: {numero}")